[package]
name = "vulfram-core"
version = "0.0.1"
edition = "2024"

[dependencies]
env_logger = "0.11"
log = "0.4"
notifica = "3.0"
once_cell = "1.21"
pollster = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
rmp-serde = "1.3.0"
wgpu = "27.0"
winit = "0.30"
gilrs = "0.11"

# Image decoding
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "avif"] }

# N-API dependencies (optional)
napi = { version = "3.6", optional = true }
napi-derive = { version = "3.4", optional = true }
mlua = { version = "0.11.5", features = ["lua54", "module"], optional = true }
pyo3 = { version = "0.27.2", features = ["extension-module"], optional = true }

[build-dependencies]
napi-build = "2.3.1"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[features]
default = ["napi"]  # Default to N-API export
ffi = []  # C ABI / FFI export
napi = ["dep:napi", "dep:napi-derive"]  # N-API export
mlua = ["dep:mlua"]
pyo3 = ["dep:pyo3"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
codegen-units = 1



