[package]
name = "vulfram-core"
version = "0.0.1"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.28"
notifica = "3.0.2"
once_cell = "1.21.3"
pollster = "0.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_cbor = "0.11.2"
serde_repr = "0.1.20"
wgpu = "27.0.1"
winit = "0.30.12"
gilrs = "0.11.0"

# Image decoding
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "avif"] }

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
codegen-units = 1


